### ISSUE TITLE
i have created an Custom Translation but unable to add it [ when pressing on ADD nothing happens ]

### ISSUE THREAD

**Issue by chriswendt1** [MicrosoftTranslator/DocumentTranslation#100]
i have created an Custom Translation but unable to add it [ when pressing on ADD nothing happends ] 
![image](https://user-images.githubusercontent.com/61323542/180183190-0a53d7b2-2c8d-4f26-b4fa-32b625f13661.png)

_Originally posted by @GlennHusseinx in https://github.com/MicrosoftTranslator/DocumentTranslation/issues/37#issuecomment-1191272739_

**Comment by chriswendt1** [comment]
In the case of no custom categories previously defined, you get should get two custom categories as a suggestion, which you can modify as you like.
![image](https://user-images.githubusercontent.com/11096941/180232868-049d4be3-faa3-495e-8f18-5af83662e10f.png)

@GlennHusseinx, can you help me debug this by going to your 
`C:\Users\,your name>\AppData\Roaming\Document Translation`
folder and delete the file `CustomCategories.json`?
Let me know if you don't have a file by that name. 

If you are in a bind to get this working quickly, you can manually add that file, here is example content:
`[
  {
    "Name": "Category 1",
    "ID": ""
  },
  {
    "Name": "Category 2",
    "ID": ""
  }
]`

**Comment by GlennHusseinx** [comment]
I have tested and it is working thank you very much
- Deleted the CustomCategories.json

adjusted it and working now.

**Comment by chriswendt1** [comment]
@GlennHusseinx, thanks a lot for your test.
I made a code change to protect against invalid CustomCategories.json content. 
In case of a parse error, showing the same default categories as with a non-existent CustomCategories.json.
