### ISSUE TITLE
EndNote plugin and other Word fields are converted  to plain text in Word document

### ISSUE THREAD

**Issue by mbalcerzyk** [MicrosoftTranslator/DocumentTranslation#102]
I have a Word docx document that has fields in it: counting of figure numbers (Field {SEQ Figure }and EndNote (www.endnote.com from Clarivate) references {ADDIN EN.CITE {ADDIN EN.CITE.DATA}} .  Even if I select the option of Ignore Hidden Text in translation of document, all these fields are lost, i.e. they are replaced by their text values. That means that the translated document looses the automation of the original one. I use version 2.9.4 of Document Translator.
Can this error be fixed in version 2 still?
Regards
Marcin B.

**Comment by chriswendt1** [comment]
Hello Marcin,

Document Translator has been archived - we will no longer work on it. It has been replaced with Document Translation - this project, where you submitted this issue. 
Could you repro your issue with Document Translation, currently at version 0.9.3.2, and let us know what you find?

Document Translati**on** works fundamentally differently from Document Translat**or**. The document decomposition and recomposition is done server-side, by the Azure Document Translation service.

**Comment by mbalcerzyk** [comment]
Hi.

I don't have sufficient Azure subscription to try it and reproduce with version 0.9. I ended up translating it with build in Translator in Word,  paragraph by paragraph,  and it respected the Word fields.

Maybe you can prepare a Word file - post a picture,  insert caption,  and use Figure {SEQ Figure} build in field. Try translating a document like that from English to Spanish,  and see if the field is maintained. If yes,  maybe I'll add to my Azure subscription this storage which is required for Translation to function.

Regards

Marcin Balcerzyk
calle Matrona Rosario Ramos 20
41909 Salteras (Sevilla)
Spain
tel. +34 955728289<tel:+34955728289>
movil +34 697 322 126<tel:+34697322126>
Skype: balcerzm

________________________________

**Comment by chriswendt1** [comment]
Check this out:
[Field Test 220811.docx](https://github.com/MicrosoftTranslator/DocumentTranslation/files/9312198/Field.Test.220811.docx)

**Comment by chriswendt1** [comment]
Not repro with Document Translation. Please upgrade.
