### ISSUE TITLE
Translate entire folder as source

### ISSUE THREAD

**Issue by mcgrovia** [MicrosoftTranslator/DocumentTranslation#104]
Using the GUI, it appears no functionality exists to add a folder for translation (?). However, the --help in doctr translate specifies that 'source' can be a folder. 

I've tried passing a folder as the source in the CLI with no luck. I've tried quotes, paths with no spaces, placing source before switches, after, and passing a folder argument via batch. Should this work or is it just an issue with --help?

I've attempted a workaround with a recursive batch call, but due to where doctr places the 'en' folder (which I like), it starts creating a nearly vertical hierarchy (folder\en\en\en etc.) My batch skills are pathetic, so I'm hoping there is support in doctr and I'm calling it incorrectly.

My goal is to iterate through a multilevel folder structure and translate all documents, placing the translated copies in 'en' subfolders at the same level as the original files within the source hierarchy.

**Comment by chriswendt1** [comment]
Passing a folder to 'doctr translate' will translate the files in the given folder. It will not recurse into the subfolders.
![image](https://user-images.githubusercontent.com/11096941/197603953-f24e828d-ed22-40ee-a91b-ae8e6fdb0b3a.png)

Does this match your observations?

We can treat as a feature request to recurse into the subfolders, maybe as an option. As you observed, putting the translated files or folder tree back into the original folder tree will cause confusion. I would in this case create the target folder on the same level as the source folder: <sourcefolder>.<language code>.

**Comment by mcgrovia** [comment]
Thank you Chris. I was getting an error that the folder was excluded due to type mismatch (the whole thing), then an error that credentials were missing (I don't get this error when running a file). Your confirmation that this should work helped me dig further. The issue may have been that the folder was copied from a mapped google drive folder (directly to a local folder). Some retained folder attribute was causing issues I think. When i copied the same files into a new folder (also C), passing the folder worked without issue (and no credential error). Regarding recursion, I made a workaround via batch (getting better at it now) to skip the \en folder. I also had it check for the existence of each file in \en before trying to translate a file in the parent to avoid translating something already completed (to maintain a 'current' translated folder with new files added to the structure). Thanks!

**Comment by chriswendt1** [comment]
Thanks for the update. Let me know if you need a change to the behavior of the document translation client.

**Comment by mcgrovia** [comment]
Thank you I will.
