### ISSUE TITLE
Custom Translate does not work for document translation but text translation

### ISSUE THREAD

**Issue by saracg** [MicrosoftTranslator/DocumentTranslation#112]
Recently our Custom Translate stopped working following an azure subscription move. Every resource was moved to the new sub. including the blob storage.

i don't know if they are related but now custom translate does not work for document translation but text translation only. when i test the settings in the document translation, it says "Test passed".  

i have tested also the language studio and unfortunately result is the same.

i have created another translation resource to test and trained it. Still no luck

**Comment by saracg** [comment]
Hi @chriswendt1 ,

it means i receive the very same document as i didnt select any category in document translation section and use normal un customized translation.

But if i copy and paste the same text and use text translation with category, results are as expected (which is the same results as it was previously giving with a "working" document translation).

Thanks for your comments, I am also suspicious about Azure as it didn't work with language studio as well. 

I will definitely let the community know about the solution once i find it.

**Comment by chriswendt1** [comment]
Hi @saracg,
I did try the app with a customized systems, and I do get documents translated with the custom version. In other words, I cannot reproduce your problem.
Please reactivate if you CAN repro using the app AND CANNOT repro using Language Studio.
