### ISSUE TITLE
HttpRequestException InnerException can be null

### ISSUE THREAD

**Issue by martinskeem** [MicrosoftTranslator/DocumentTranslation#114]
The InnerException referenced here can be null raising an uncaught exception and for the application to shut down

https://github.com/MicrosoftTranslator/DocumentTranslation/blob/2589f9bfcb1cf25c057e4ded356d745ff8277f60/DocumentTranslation.GUI/MainWindow.xaml.cs#LL704C40-L704C58

Furthremore, the exception can contain a useful message. I propose doing this instead:
```c#
StatusBarSText2.Text = $"{ex.InnerException?.Message}. {ex.Message}";
``` 

I would also like to open a PR to fix this if you accept that.

**Comment by chriswendt1** [comment]
I agree with your proposal. I will accept your PR.

**Comment by martinskeem** [comment]
Added the PR and associated it to this issue. Let me know what you think.

**Comment by chriswendt1** [comment]
Merged into master. 
I changed the layout a bit to keep Experimental settings at the bottom.
