### ISSUE TITLE
Unable to locate DocumentTranslation Privacy Policy

### ISSUE THREAD

**Issue by RichardsIT1984** [MicrosoftTranslator/DocumentTranslation#121]
Where is the Privacy Policy for DocumentTranslation located? 

<img width="959" alt="Microsoft DocumentTranslator Privacy Policy Search" src="https://github.com/MicrosoftTranslator/DocumentTranslation/assets/117313574/a6789abe-0461-46c9-9add-25cf5592b02d">

**Comment by chriswendt1** [comment]
The Document Translator app is a simple, open-source front-end to the Azure Translator service. The data handling policies are covered by Azure privacy regulation: https://azure.microsoft.com/en-us/explore/trusted-cloud/privacy/.

**Comment by chriswendt1** [comment]
I added security and privacy documentation to README. Let me know if this addresses your request.

**Comment by chriswendt1** [comment]
@RichardsIT1984 
I added security and privacy documentation to README. Let me know if this addresses your request.

**Comment by RichardsIT1984** [comment]
Hello Chris,

Thank you so much for your time. The Privacy and Security<https://github.com/MicrosoftTranslator/DocumentTranslation#privacy-and-security> addition to the README.md is just what I was looking for.

Thank you so much for all your hard work on this project!

***@***.***

**Comment by chriswendt1** [comment]
@RichardsIT1984,  thank you for confirming.
