### ISSUE TITLE
The agent is killed while testing

### ISSUE THREAD

**Issue by valilazarov** [MicrosoftTranslator/DocumentTranslation#125]
I've tried to test the client (doc. translation) on a Windows machine- all settings are in place , but during testing the software is killed. 

I am behind a VPN - can be this the route cause?

**Comment by chriswendt1** [comment]
Hi @valilazarov , thanks for the feedback. The VPN by itself should not do harm, but a firewall may be blocking access to the service URLs the client is using.
Can you add a description of what happened before the crash?

**Comment by chriswendt1** [comment]
Log is in C:\Users\<user>\AppData\Roaming\Document Translation\doctrLog.txt
Can you enter and [Test] your credentials? Does the test pass?

**Comment by valilazarov** [comment]
No logs available as file is not existing, the agent is crashing during testing...I suspect a VPN drop.

**Comment by valilazarov** [comment]
I am  using the complete credentials - the correct one for sure. After pressing save and testing button the app crashes.

**Comment by chriswendt1** [comment]
@valilazarov  Thanks. I'll have a look.

**Comment by chriswendt1** [comment]
Hi @valilazarov,

Can you run this command on the command line and see what happens?
`doctr config test`

![image](https://github.com/MicrosoftTranslator/DocumentTranslation/assets/11096941/61c80f2f-7134-4a87-8e10-889a2193bcec)

I built an unsigned version that catches some additional exceptions in the test phase. Hopefully this will reveal something. 

[Uploading DocumentTranslationTest 1.0.2.1.zip…]()

Let us know what you find.

**Comment by valilazarov** [comment]
Hi @chriswendt1  - thanks a lot! The output is pointing to "Unhandled exception. System.Net.Http.HttpRequestException: The proxy tunnel request to proxy ...failed with status code '407'."" . My assumption was correct: the VPN is dropping the connections. I'll talk with the network team to allow the connections.

Thanks a lot for support!

**Comment by chriswendt1** [comment]
Thanks, @valilazarov . How did you find this? Did you have to run the updated Windows app, or was the command line enough to show you this message?

**Comment by valilazarov** [comment]
@chriswendt1 , the command line was enough.

**Comment by chriswendt1** [comment]
Thanks a lot, @valilazarov .
Could you still do me a favor and run the above attached binary version 1.0.2.1 before you change the proxy? 
I expect it to not crash and instead display the proxy failure 407 message in the status bar.

**Comment by valilazarov** [comment]
Indeed. The proxy failure 407 is showned in the status bar after the update to 1.0.2.1. @chriswendt1, great job!

**Comment by chriswendt1** [comment]
Excellent. @valilazarov, thanks for letting me know. I have checked in this change. 
Your IT team can fix the problem by permitting the Azure domains in the proxy's firewall settings.
