### ISSUE TITLE
Need the translated version editable

### ISSUE THREAD

**Issue by rohit2git** [MicrosoftTranslator/DocumentTranslation#129]
If we translate a PDF, it outputs PDF which is great. But the PDF output is misaligned at some sections where text is not readable from source pdf. So can we also have out put of translation in WORD document preserving the text style and formatting? Is it possible or upcoming?

**Comment by chriswendt1** [comment]
You can use Adobe Acrobat to edit the PDF directly or export the PDF into a Word document from Acrobat.

**Comment by rohit2git** [comment]
Thanks, but it would be great if it can be done programmatically.

**Comment by chriswendt1** [comment]
I understand the request, but this tool is solely meant for translation. Format conversion is a different matter.
