### ISSUE TITLE
Is it safe enough to use it in a company and prevent information leakage？

### ISSUE THREAD

**Issue by FengChangJeff** [MicrosoftTranslator/DocumentTranslation#130]
Hi Sir,
@chriswendt1 Is it safe enough to use it in a company and prevent information leakage？Where the docs or text will be storaged?

Regards,

**Comment by chriswendt1** [comment]
Hi Jeff,

Yes, it is safe enough for corporate use. Please choose authentication via Keyvault to avoid storing keys on the client device.
You may have the security and privacy documentation reviewed by your corporate infosec contact:

https://github.com/MicrosoftTranslator/DocumentTranslation#privacy-and-security

#121
