### ISSUE TITLE
What file formats are supported?

### ISSUE THREAD

**Issue by parclarke** [MicrosoftTranslator/DocumentTranslation#16]
What file formats are supported and how to you set them in the appsettings.json file?

**Comment by chriswendt1** [comment]
You can use the "doctr formats" command to retrieve the list of file formats.
The output currently is:
```
>doctr formats
CSV     .csv
ExcelSpreadsheet        .xls
HtmlFile        .html   .htm
Markdown        .markdown       .mdown  .mkdn   .md     .mkd    .mdwn   .mdtxt  .mdtext .rmd
Mhtml   .mhtml  .mht
OpenDocumentPresentation        .odp
OpenDocumentSpreadsheet .ods
OpenDocumentText        .odt
OpenXmlPresentation     .pptx
OpenXmlSpreadsheet      .xlsx
OpenXmlWord     .docx
OutlookMailMessage      .msg
PlainText       .txt
PortableDocumentFormat  .pdf
PowerpointPresentation  .ppt
RichTextFormat  .rtf
TSV     .tsv    .tab
WordDocument    .doc
XLIFF   .xlf
```
You do not need to set the file format individually. File format is determined by the extension. 
The list of formats is purely determined by the service.
An upcoming enhancement is a mechanism to add local pre-and post-processing for additional file formats. Top candidate is VTT/SRT file format.

**Comment by chriswendt1** [comment]
Milestone work is to add this to the README.

**Comment by parclarke** [comment]
Wow! That is a lot of formats. I was not expecting that. I read there is a 5000 character limit to the amount of text you can translate. Does that limitation apply to this project? Here is the error I am getting: doctr formats
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at TranslationService.CLI.Program.<>c.<<Main>b__1_19>d.MoveNext() in C:\work\Source\Repos\DocumentTranslation\DocumentTranslation.CLI\Program.cs:line 253

**Comment by chriswendt1** [comment]
This is using Microsoft's document translation service, which has different request limits. The limits are listed here:
https://docs.microsoft.com/en-us/azure/cognitive-services/translator/document-translation/get-started-with-document-translation?tabs=csharp#content-limits

Thank you, I will fix this crash.
This commend requires the complete set of credentials and doesn't behave well otherwise :-(

**Comment by chriswendt1** [comment]
Updated the documentation with more detailed instructions on how to obtain credentials, and how to find the supported document formats.

**Comment by parclarke** [comment]
I am still getting a Null Reference Exception when I execute doctr formats. I'm suspecting something is missing in my appsettings file Program.cs:line 253

**Comment by chriswendt1** [comment]
Did you rebuild or use a provided binary?
I just uploaded doctr.zip, compiled from current master branch, to 
https://github.com/MicrosoftTranslator/DocumentTranslation/releases/edit/0.2.0.0

**Comment by parclarke** [comment]
I did a Git Pull and recompiled the solution. I will try the zip file.

**Comment by chriswendt1** [comment]
That should have worked. The current code?
There is nothing particularly interesting happening around line 253, and nothing to do with formats.
![image](https://user-images.githubusercontent.com/11096941/120854066-7613a380-c531-11eb-9f87-ea8cb3073ffa.png)

**Comment by parclarke** [comment]
Using the new zip file under releases I'm getting the following error: List of translatable extensions cannot be null. (Parameter 'Extensions')

Using the GUI this is the error I'm getting 
[
![Capture](https://user-images.githubusercontent.com/10340428/120854553-54bfb100-c54b-11eb-8306-e656696df581.PNG)
](url)

**Comment by chriswendt1** [comment]
When you "Test" your credentials, do get a pass?
doctr config test
or
"Test" button in the GUI's Authentication page.

**Comment by parclarke** [comment]
Yes I get a PASS

**Comment by chriswendt1** [comment]
That is good. Wild theories:
- Your key is not for the Translator resource, but a different one or an All-In-One key.
- The key is for a different Translator resource than the one you gave the name for.

The storage account shouldn't matter, don't need a storage account for enumerating the formats/

**Comment by parclarke** [comment]
My apologies. I was using a Cognitive Services key and not a Translator service key. It is working fine now. The funny thing is that when I used the Cognitive services key I could translate text using the GUI app.

**Comment by chriswendt1** [comment]
OK, thanks. No surprise that the Text Translation worked - it is less sensitive to the key type.
Bug that the "Test" let you pass.
I will repro with your scenario and then try and catch the empty response. 
Thanks for the report, and let me know what else you find.

**Comment by chriswendt1** [comment]
I am getting a "Test failed" result with the Cognitive Services key. 

![image](https://user-images.githubusercontent.com/11096941/120871362-49bb4f80-c550-11eb-826e-80c64b8399a4.png)

![image](https://user-images.githubusercontent.com/11096941/120871351-3e682400-c550-11eb-8f8d-ee45de0a6fbc.png)

**Comment by chriswendt1** [comment]
Thanks again for the  help. I updated the code to catch the failure with a Cognitive Services key. Binaries not updated.
Let me know what else you find.

**Comment by akostadinov** [comment]
Anybody had success with RTF? Even the simplest RTF gets HTTP 400 for me. For example put this as the content of a file `test.rtf`:
```
{\rtf1\ansi\deff0 {\fonttbl {\f0 Times New Roman;}} Hello world}
```

**Comment by chriswendt1** [comment]
@akostadinov It works for me:

<img width="1045" height="752" alt="Image" src="https://github.com/user-attachments/assets/f8cf08a5-c405-4301-9bc8-ce16c7a86c08" />

The source is UTF-8 encoded. I used Notepad++ to create the RTF file with your sample text. Encoded in UTF-8. I used another RTF file created with Word.
The target file for RTF source will be in DOCX format.
