### ISSUE TITLE
Translation using custom models is not working

### ISSUE THREAD

**Issue by krishna-doss-mohan** [MicrosoftTranslator/DocumentTranslation#35]
Translation using custom models is not working - tested for text translation

**Comment by chriswendt1** [comment]
@krishna-doss-mohan 
Can you add some more info here, what you tried and what was the result?
I had verified that the category parameter gets properly transmitted. 
Please attach the log file C:\Users\wendt\AppData\Roaming\Document Translation\doctrLog.txt. it shows includes the exact translation request.
