### ISSUE TITLE
Fails to run after initial install - Test failedkey

### ISSUE THREAD

**Issue by davidhanna66** [MicrosoftTranslator/DocumentTranslation#40]
After installing and adding configurations, app closed twice after clicking Save and Test. Now I have entered service key, region, endpoint and I am receiving error Test failedkey. I have entered values as described in docs.

**Comment by chriswendt1** [comment]
Thanks for the report.
Could it be that the key is for a different region than selected, or for a different resource? Needs to be for a Translator resource, not one for Cognitive Services. 
If region and resource are correct, can you tell me which region?

Also, when the app terminated, did you see the call stack?

**Comment by davidhanna66** [comment]
Hi Chris- Hope you are doing well.

The key was from EUS2. I even put storage account there just in case.

I did not see call stack.

***@***.******@***.***D76C41.17CCF0E0]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by chriswendt1** [comment]
OK, thanks. Let me try EUS2 and see what the problem is...
If you need a quick resolution, try "Global", if you can.

**Comment by chriswendt1** [comment]
I can repro the problem.

**Comment by chriswendt1** [comment]
Document Translation will work regardless. Text translation will fail for anything but "Global". Easy fix. Fixing...
Other problems:  When attempting text translation, the error appears in the result. Expected: status bar.
I would not repro the unexpected application exit.

**Comment by chriswendt1** [comment]
Fixed in version 0.7.0.3 Let me know how it goes.

**Comment by chriswendt1** [comment]
Updated binary as release 0.2.0.4.

**Comment by chriswendt1** [comment]
Hi @davidhanna66 , can you let me know whether this fixed your issue? Are you unblocked now?
