### ISSUE TITLE
Standard subscription required for document translation

### ISSUE THREAD

**Issue by erickaleida** [MicrosoftTranslator/DocumentTranslation#47]
I was receiving a 403 error when trying to translate documents.  I was using the Free pricing tier for the Azure Translator and document translation requires the Standard pricing tier.  This should be indicated in the setup documentation.

**Comment by chriswendt1** [comment]
Good point, thank you.
Plan:
- Update the documentation
- Catch 403 error and produce appropriate message

**Comment by chriswendt1** [comment]
Documentation is fixed.

**Comment by chriswendt1** [comment]
Fixed UI message.
Remaining: Proper test under the Settings.Test button action.

**Comment by chriswendt1** [comment]
Fixed in 0.8.0.1
