### ISSUE TITLE
Trouble running the project in visual studio code 

### ISSUE THREAD

**Issue by workingonit123** [MicrosoftTranslator/DocumentTranslation#64]
Hi! I'm trying to open and run the DocumentTranslation-master code in visual studio to customize the dashboard. After opening the folder in visual studio, and running it, I get the errors:

The type or namespace name 'DocumentTranslationService' could not be found (are you missing a using directive or an assembly reference?) [doctr]

The type or namespace name 'DocTransAppSettings' could not be found (are you missing a using directive or an assembly reference?) [doctr]

The name 'AppSettingsSetter' does not exist in the current context [doctr]

May you please give some guidance on how to open and run the code in visual studio. Thank you for your time! I appreciate it

**Comment by chriswendt1** [comment]
No response.
I am building with the full version of Visual Studio. 
Closing.
