### ISSUE TITLE
Crash error 

### ISSUE THREAD

**Issue by Band-Aid** [MicrosoftTranslator/DocumentTranslation#76]
Document Translation silently crashes with the following in event viewer

```
Application: DocumentTranslation.GUI.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

```
Faulting application name: DocumentTranslation.GUI.exe, version: 0.0.8.0, time stamp: 0x61e1d8d9
Faulting module name: KERNELBASE.dll, version: 10.0.22000.434, time stamp: 0x72a6f702
Exception code: 0xe0434352
Fault offset: 0x000000000004478c
Faulting process id: 0xdfc
Faulting application start time: 0x01d82661c3eeb71c
Faulting application path: C:\Program Files (x86)\Document Translation\DocumentTranslation.GUI.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 97cecc0a-4ef3-45cb-aef3-da9d84ed3dd8
Faulting package full name: 
Faulting package-relative application ID: 
```

Edition	Windows 11 Enterprise
Version	21H2
Installed on	‎12/‎31/‎2021
OS build	22000.493
Experience	Windows Feature Experience Pack 1000.22000.493.0

**Comment by chriswendt1** [comment]
Hi Band-Aid, thanks for the report.
This looks like it would be a .Net 6 issue, and probably not under the control of the app.
Could you try an uninstall of the ,Net 6 runtime, and manually reinstall .Net 6.0.2 from https://dotnet.microsoft.com/en-us/download/dotnet/6.0?

If you are in a crunch and don't want to spend the time, try the command line version.

**Comment by Band-Aid** [comment]
thanks. so I had 6.0.1 installed but .net was asking for .6.0.2 and seems like it is not backwards compatible. Upgrading to 6.0.2 fixed the issue.
This happened on different machines I tested so, it's not environment specific.
It might be worth noting in your readme 6.0.2 is required :) Thanks

**Comment by chriswendt1** [comment]
Or let Windows Update keep it up to date for you.
