### ISSUE TITLE
"Service request failed." message when translating docs. Could be more meaningful.

### ISSUE THREAD

**Issue by chriswendt1** [MicrosoftTranslator/DocumentTranslation#87]
"Service request failed." message when translating documents. Text translation works.
Try to return a more helpful error message, maybe kicking off the test code of the Settings page. 
@krishna-doss-mohan 

![image](https://user-images.githubusercontent.com/11096941/167896052-6231c942-c994-437d-b11a-ede9c7be21f1.png)

**Comment by chriswendt1** [comment]
Could not repro the original problem by falsifying the individual settings. Added some extra checks and made the Key Vault functionality more robust.
Will be in version 0.9.2.0.

**Comment by jfgomezok** [comment]
Hi Chris. I'm having the same issue (running version 0.9.3.2 in Windows 11). I can translate text, but when I click in "Select" in the Translate Documents tab, am having the same message ("Error   Service Request Failed"). Any ideas? Thanks!

**Comment by chriswendt1** [comment]
I'll add some checks to the **Test** function.
