### ISSUE TITLE
Glossary not taking all words into account?

### ISSUE THREAD

**Issue by AtlasDevAccount** [MicrosoftTranslator/DocumentTranslation#90]
I created a .tsv with 
en	de
apple tech news	apple tech news

However when I translate a word .docx that has the phrase 'Apple Tech News' it is translated to 'Apple Tech Neuigkeiten' instead of what I would like it to be which is 'Apple Tech News' Any ideas why this is happening?

**Comment by chriswendt1** [comment]
The glossary is case sensitive.

**Comment by chriswendt1** [comment]
@AtlasDevAccount,
Can you confirm that you were able to fix this by adding case-matching glossary entries?
If not, please reactivate this issue.
