### ISSUE TITLE
services your current subscription sku is not supported by this service

### ISSUE THREAD

**Issue by yackzel** [MicrosoftTranslator/DocumentTranslation#94]
When I do a test it returns an error message saying:

services your current subscription sku is not supported by this service

I think it is because I selected the free tier.  Is there a way to test this out with the free tier?

**Comment by chriswendt1** [comment]
Hi @yackzel ,

Document Translation will not work with the free tier,
You need to have at least an S1 subscription (paid) to the Translator resource, and it needs to be a direct subscription, not as a bundle, and it cannot be a free subscription. 

You subscribe to S1, do your test, and then immediately unsubscribe. You will be charged only for the few characters you consumed. 

Does that work?

**Comment by yackzel** [comment]
> Hi @yackzel ,
> 
> Document Translation will not work with the free tier, You need to have at least an S1 subscription (paid) to the Translator resource, and it needs to be a direct subscription, not as a bundle, and it cannot be a free subscription.
> 
> You subscribe to S1, do your test, and then immediately unsubscribe. You will be charged only for the few characters you consumed.
> 
> Does that work?

Yes, I did that to test it and it worked.  Thanks for the help appreciated

**Comment by chriswendt1** [comment]
OK, thanks. Let me know of any other issues you find.
