### ISSUE TITLE
i18n support?

### ISSUE THREAD

**Issue by johnfelipe** [MicrosoftTranslator/DocumentTranslation#96]

**Comment by chriswendt1** [comment]
Hi @johnfelipe, please elaborate. Do you mean UI localization of the app itself?

The UI strings are stored in resource files. It is easy to add additional resource files for languages besides English.

**Comment by johnfelipe** [comment]
Can u share me path pls
I want contribute with es, fr and it

**Comment by chriswendt1** [comment]
Translate resources.resx.
I will make sure it gets loaded properly at runtime.

**Comment by johnfelipe** [comment]
Path pls, i cant found it

**Comment by chriswendt1** [comment]
https://github.com/MicrosoftTranslator/DocumentTranslation/blob/master/DocumentTranslation.GUI/Properties/Resources.resx

**Comment by chriswendt1** [comment]
I added machine translated resources files with the correct name and location, which you can edit:
Spanish: https://github.com/MicrosoftTranslator/DocumentTranslation/blob/master/DocumentTranslation.GUI/Properties/Resources.es-es.resx
French: https://github.com/MicrosoftTranslator/DocumentTranslation/blob/master/DocumentTranslation.GUI/Properties/Resources.fr-fr.resx
Italian: https://github.com/MicrosoftTranslator/DocumentTranslation/blob/master/DocumentTranslation.GUI/Properties/Resources.it-it.resx

I also added de-de, which I post-edited lightly. 

Let me know when you are done.

**Comment by johnfelipe** [comment]
i want to do, yes, but pls tell me wich engine use for machine translation?
azure
ibm
google?

**Comment by chriswendt1** [comment]
Hi @johnfelipe, where are you with this?

**Comment by johnfelipe** [comment]
My notebook is in maintaining
