### ISSUE TITLE
CLI version for ubuntu 20

### ISSUE THREAD

**Issue by johnfelipe** [MicrosoftTranslator/DocumentTranslation#98]
is possible have this perfect desktop application in console enviroment.
For example for markdown translation im use 

https://github.com/menthays/markdown-translator

next import API from azure

next i upload folders and files for translate

`md-translator translate --src configure-data-sources.md --dest configure-data-sources.es.md --from en --to es`

and obtain tanslation

Is possible have this for all files supported in this repo?

**Comment by chriswendt1** [comment]
For Ubuntu, follow the steps for Mac OS X:
https://microsofttranslator.github.io/DocumentTranslation/#running-on-mac-os-x

The app translates MD files as is, no additional processing needed.
